//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditorium
    {
        public Auditorium()
        {
            this.GamesCycles = new HashSet<GamesCycle>();
            this.TeamsAuditoriums = new HashSet<TeamsAuditorium>();
        }
    
        public int AuditoriumId { get; set; }
        public Nullable<int> UnionId { get; set; }
        public string Name { get; set; }
        public bool IsArchive { get; set; }
        public string Address { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> ClubId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Season Season { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<GamesCycle> GamesCycles { get; set; }
        public virtual ICollection<TeamsAuditorium> TeamsAuditoriums { get; set; }
    }
}
