//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public Club()
        {
            this.ClubTeams = new HashSet<ClubTeam>();
            this.Leagues = new HashSet<League>();
            this.Seasons = new HashSet<Season>();
            this.SentMessages = new HashSet<SentMessage>();
            this.TeamStandingGames = new HashSet<TeamStandingGame>();
            this.Auditoriums = new HashSet<Auditorium>();
            this.Events = new HashSet<Event>();
        }
    
        public int ClubId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public string Name { get; set; }
        public bool IsArchive { get; set; }
        public string Logo { get; set; }
        public string PrimaryImage { get; set; }
        public string Description { get; set; }
        public string IndexImage { get; set; }
        public string IndexAbout { get; set; }
        public string TermsCondition { get; set; }
        public string ContactPhone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<bool> IsSectionClub { get; set; }
        public Nullable<bool> IsUnionClub { get; set; }
        public Nullable<int> SportCenterId { get; set; }
        public Nullable<int> NGO_Number { get; set; }
        public Nullable<int> SeasonId { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<ClubTeam> ClubTeams { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
        public virtual ICollection<Season> Seasons { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual SportCenter SportCenter { get; set; }
        public virtual ICollection<TeamStandingGame> TeamStandingGames { get; set; }
        public virtual ICollection<Auditorium> Auditoriums { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
