//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ContId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int StateId { get; set; }
        public bool IsArchive { get; set; }
        public int TypeId { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> LockedById { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ContentState ContentState { get; set; }
        public virtual ContentType ContentType { get; set; }
    }
}
