//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactId { get; set; }
        public string FullName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        public System.DateTime SendDate { get; set; }
        public bool IsArchive { get; set; }
        public bool IsDone { get; set; }
        public Nullable<System.DateTime> DoneDate { get; set; }
        public bool IsGetAds { get; set; }
        public Nullable<int> CampId { get; set; }
        public bool IsMobile { get; set; }
        public string UserIP { get; set; }
    }
}
