//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public Nullable<int> LeagueId { get; set; }
        public string Title { get; set; }
        public System.DateTime EventTime { get; set; }
        public string Place { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsPublished { get; set; }
        public Nullable<int> ClubId { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual League League { get; set; }
    }
}
