//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventsLog
    {
        public int LogId { get; set; }
        public string EventType { get; set; }
        public System.DateTime EventDate { get; set; }
        public string Description { get; set; }
    }
}
