//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int GameId { get; set; }
        public int LeagueId { get; set; }
        public int Rounds { get; set; }
        public int PlayoffTeamsNum { get; set; }
        public int WeekRounds { get; set; }
        public string GameDays { get; set; }
        public System.DateTime StartDate { get; set; }
        public string GamesInterval { get; set; }
        public int PointsWin { get; set; }
        public int PointsDraw { get; set; }
        public int PointsLoss { get; set; }
        public int GroupsNum { get; set; }
        public Nullable<int> NumberOfSequenceRounds { get; set; }
        public string SortDescriptors { get; set; }
        public int PointsTechWin { get; set; }
        public int PointsTechLoss { get; set; }
        public Nullable<int> StageId { get; set; }
        public Nullable<int> SeasonId { get; set; }
    
        public virtual League League { get; set; }
        public virtual Season Season { get; set; }
    }
}
