//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesCycle
    {
        public GamesCycle()
        {
            this.GameSets = new HashSet<GameSet>();
            this.NotesGames = new HashSet<NotesGame>();
            this.WallThreads = new HashSet<WallThread>();
            this.Users = new HashSet<User>();
        }
    
        public int CycleId { get; set; }
        public int StageId { get; set; }
        public int CycleNum { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> AuditoriumId { get; set; }
        public Nullable<int> GuestTeamId { get; set; }
        public int GuestTeamScore { get; set; }
        public Nullable<int> HomeTeamId { get; set; }
        public int HomeTeamScore { get; set; }
        public Nullable<int> RefereeId { get; set; }
        public Nullable<int> GroupeId { get; set; }
        public string GameStatus { get; set; }
        public Nullable<int> TechnicalWinnnerId { get; set; }
        public Nullable<int> MaxPlayoffPos { get; set; }
        public Nullable<int> MinPlayoffPos { get; set; }
        public Nullable<int> BracketId { get; set; }
        public bool IsPublished { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Team GuestTeam { get; set; }
        public virtual Team HomeTeam { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<GameSet> GameSets { get; set; }
        public virtual PlayoffBracket PlayoffBracket { get; set; }
        public virtual ICollection<NotesGame> NotesGames { get; set; }
        public virtual ICollection<WallThread> WallThreads { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual Auditorium Auditorium { get; set; }
    }
}
