//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupsTeams = new HashSet<GroupsTeam>();
            this.GamesCycles = new HashSet<GamesCycle>();
            this.PlayoffBrackets = new HashSet<PlayoffBracket>();
        }
    
        public int GroupId { get; set; }
        public int StageId { get; set; }
        public int TypeId { get; set; }
        public string Name { get; set; }
        public bool IsArchive { get; set; }
        public Nullable<int> NumberOfCycles { get; set; }
        public bool IsAdvanced { get; set; }
        public Nullable<int> PointEditType { get; set; }
        public Nullable<int> SeasonId { get; set; }
    
        public virtual GamesType GamesType { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual ICollection<GroupsTeam> GroupsTeams { get; set; }
        public virtual ICollection<GamesCycle> GamesCycles { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets { get; set; }
        public virtual Season Season { get; set; }
    }
}
