//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.UsersJobs = new HashSet<UsersJob>();
        }
    
        public int JobId { get; set; }
        public Nullable<int> SectionId { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string JobName { get; set; }
        public bool IsArchive { get; set; }
    
        public virtual JobsRole JobsRole { get; set; }
        public virtual Section Section { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
    }
}
