//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public League()
        {
            this.Games = new HashSet<Game>();
            this.LeaguesDocs = new HashSet<LeaguesDoc>();
            this.LeagueTeams = new HashSet<LeagueTeams>();
            this.Stages = new HashSet<Stage>();
            this.TeamsFans = new HashSet<TeamsFan>();
            this.UsersJobs = new HashSet<UsersJob>();
            this.SentMessages = new HashSet<SentMessage>();
            this.Events = new HashSet<Event>();
        }
    
        public int LeagueId { get; set; }
        public Nullable<int> UnionId { get; set; }
        public int GenderId { get; set; }
        public int AgeId { get; set; }
        public string Name { get; set; }
        public string Logo { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public string Terms { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsArchive { get; set; }
        public Nullable<int> Place { get; set; }
        public Nullable<bool> EilatTournament { get; set; }
        public short SortOrder { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public int MaximumHandicapScoreValue { get; set; }
        public string AboutLeague { get; set; }
        public string LeagueStructure { get; set; }
    
        public virtual Age Age { get; set; }
        public virtual ICollection<Game> Games { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<LeaguesDoc> LeaguesDocs { get; set; }
        public virtual ICollection<LeagueTeams> LeagueTeams { get; set; }
        public virtual ICollection<Stage> Stages { get; set; }
        public virtual ICollection<TeamsFan> TeamsFans { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual Season Season { get; set; }
        public virtual Club Club { get; set; }
        public virtual ICollection<Event> Events { get; set; }
    }
}
