//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Body { get; set; }
        public int Type { get; set; }
        public int SenderId { get; set; }
        public Nullable<int> ThreadId { get; set; }
    
        public virtual User User { get; set; }
        public virtual WallThread WallThread { get; set; }
    }
}
