//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesGame
    {
        public int Id { get; set; }
        public Nullable<int> CycleId { get; set; }
        public System.DateTime SendDate { get; set; }
    
        public virtual GamesCycle GamesCycle { get; set; }
    }
}
