//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotesMessage
    {
        public NotesMessage()
        {
            this.NotesRecipients = new HashSet<NotesRecipient>();
            this.SentMessages = new HashSet<SentMessage>();
            this.Teams = new HashSet<Team>();
        }
    
        public int MsgId { get; set; }
        public string Message { get; set; }
        public int TypeId { get; set; }
        public System.DateTime SendDate { get; set; }
    
        public virtual ICollection<NotesRecipient> NotesRecipients { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
