//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    
    public enum NotificationServiceType : int
    {
        ADM = 10000,
        APNS = 20000,
        Baidu = 30000,
        GCM = 40000,
        MPNS = 50000,
        WNS = 60000
    }
}
