//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayoffBracket
    {
        public PlayoffBracket()
        {
            this.GamesCycles = new HashSet<GamesCycle>();
            this.PlayoffBrackets1 = new HashSet<PlayoffBracket>();
            this.PlayoffBrackets11 = new HashSet<PlayoffBracket>();
        }
    
        public int Id { get; set; }
        public int MaxPos { get; set; }
        public int MinPos { get; set; }
        public Nullable<int> Team1Id { get; set; }
        public Nullable<int> Team2Id { get; set; }
        public Nullable<int> WinnerId { get; set; }
        public Nullable<int> LoserId { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> ParentBracket1Id { get; set; }
        public Nullable<int> ParentBracket2Id { get; set; }
        public int Type { get; set; }
        public int Stage { get; set; }
    
        public virtual ICollection<GamesCycle> GamesCycles { get; set; }
        public virtual Group Group { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets1 { get; set; }
        public virtual PlayoffBracket PlayoffBracket1 { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets11 { get; set; }
        public virtual PlayoffBracket PlayoffBracket2 { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Team Team2 { get; set; }
        public virtual Team Team3 { get; set; }
    }
}
