//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerHistory
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int TeamId { get; set; }
        public int SeasonId { get; set; }
        public long TimeStamp { get; set; }
    
        public virtual Team Teams { get; set; }
        public virtual User Users { get; set; }
        public virtual Season Seasons { get; set; }
    }
}
