//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Season
    {
        public Season()
        {
            this.ClubTeams = new HashSet<ClubTeam>();
            this.Games = new HashSet<Game>();
            this.Groups = new HashSet<Group>();
            this.GroupsTeams = new HashSet<GroupsTeam>();
            this.PlayerHistories = new HashSet<PlayerHistory>();
            this.SentMessages = new HashSet<SentMessage>();
            this.TeamsDetails = new HashSet<TeamsDetails>();
            this.TeamsPlayers = new HashSet<TeamsPlayer>();
            this.Leagues = new HashSet<League>();
            this.UsersJobs = new HashSet<UsersJob>();
            this.Auditoriums = new HashSet<Auditorium>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> UnionId { get; set; }
        public Nullable<int> ClubId { get; set; }
    
        public virtual ICollection<ClubTeam> ClubTeams { get; set; }
        public virtual ICollection<Game> Games { get; set; }
        public virtual ICollection<Group> Groups { get; set; }
        public virtual ICollection<GroupsTeam> GroupsTeams { get; set; }
        public virtual ICollection<PlayerHistory> PlayerHistories { get; set; }
        public virtual Union Union { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<TeamsDetails> TeamsDetails { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual Club Club { get; set; }
        public virtual ICollection<Auditorium> Auditoriums { get; set; }
    }
}
