//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.Unions = new HashSet<Union>();
            this.Jobs = new HashSet<Job>();
            this.Positions = new HashSet<Position>();
            this.Clubs = new HashSet<Club>();
        }
    
        public int SectionId { get; set; }
        public int LangId { get; set; }
        public string Name { get; set; }
        public string Alias { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual ICollection<Union> Unions { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<Position> Positions { get; set; }
        public virtual ICollection<Club> Clubs { get; set; }
    }
}
