//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public int PushInterval { get; set; }
        public string ContactEmail { get; set; }
        public string SupportEmail { get; set; }
        public int KnessLawsCount { get; set; }
        public System.DateTime LastTaskRun { get; set; }
        public string BgVideo { get; set; }
        public decimal PlaybackRate { get; set; }
        public decimal PlayOpacity { get; set; }
        public string FbUrl { get; set; }
        public string MetaTitle { get; set; }
        public string MetaDescription { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Sctipts { get; set; }
    }
}
