//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamScheduleScrapper
    {
        public int Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public string HomeTeam { get; set; }
        public string GuestTeam { get; set; }
        public string Score { get; set; }
        public string Auditorium { get; set; }
        public int SchedulerScrapperGamesId { get; set; }
    
        public virtual TeamScheduleScrapperGame TeamScheduleScrapperGame { get; set; }
    }
}
