//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamStandingGame
    {
        public TeamStandingGame()
        {
            this.TeamStandings = new HashSet<TeamStanding>();
        }
    
        public int Id { get; set; }
        public string GamesUrl { get; set; }
        public int TeamId { get; set; }
        public Nullable<int> ClubId { get; set; }
        public string ExternalTeamName { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual ICollection<TeamStanding> TeamStandings { get; set; }
        public virtual Club Club { get; set; }
    }
}
