//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamsPlayer
    {
        public int Id { get; set; }
        public int TeamId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> PosId { get; set; }
        public int ShirtNum { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> SeasonId { get; set; }
        public bool IsPlayereInTeamLessThan3year { get; set; }
        public int HandicapLevel { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Team Team { get; set; }
        public virtual User User { get; set; }
        public virtual Season Season { get; set; }
    }
}
