//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.GroupsTeams = new HashSet<GroupsTeam>();
            this.TeamsAuditoriums = new HashSet<TeamsAuditorium>();
            this.TeamsFans = new HashSet<TeamsFan>();
            this.TeamsPlayers = new HashSet<TeamsPlayer>();
            this.GuestTeamGamesCycles = new HashSet<GamesCycle>();
            this.HomeTeamGamesCycles = new HashSet<GamesCycle>();
            this.PlayoffBrackets = new HashSet<PlayoffBracket>();
            this.PlayoffBrackets1 = new HashSet<PlayoffBracket>();
            this.PlayoffBrackets2 = new HashSet<PlayoffBracket>();
            this.PlayoffBrackets3 = new HashSet<PlayoffBracket>();
            this.WallThreads = new HashSet<WallThread>();
            this.ClubTeams = new HashSet<ClubTeam>();
            this.LeagueTeams = new HashSet<LeagueTeams>();
            this.PlayerHistory = new HashSet<PlayerHistory>();
            this.TeamsDetails = new HashSet<TeamsDetails>();
            this.UsersJobs = new HashSet<UsersJob>();
            this.SentMessages = new HashSet<SentMessage>();
            this.TeamStandingGames = new HashSet<TeamStandingGame>();
            this.NotesMessages = new HashSet<NotesMessage>();
        }
    
        public int TeamId { get; set; }
        public string Title { get; set; }
        public string Logo { get; set; }
        public string PersonnelPic { get; set; }
        public string Description { get; set; }
        public string OrgUrl { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsArchive { get; set; }
        public string GamesUrl { get; set; }
        public Nullable<bool> IsUnderAdult { get; set; }
        public Nullable<bool> IsReserved { get; set; }
    
        public virtual ICollection<GroupsTeam> GroupsTeams { get; set; }
        public virtual ICollection<TeamsAuditorium> TeamsAuditoriums { get; set; }
        public virtual ICollection<TeamsFan> TeamsFans { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers { get; set; }
        public virtual ICollection<GamesCycle> GuestTeamGamesCycles { get; set; }
        public virtual ICollection<GamesCycle> HomeTeamGamesCycles { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets1 { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets2 { get; set; }
        public virtual ICollection<PlayoffBracket> PlayoffBrackets3 { get; set; }
        public virtual ICollection<WallThread> WallThreads { get; set; }
        public virtual ICollection<ClubTeam> ClubTeams { get; set; }
        public virtual ICollection<LeagueTeams> LeagueTeams { get; set; }
        public virtual ICollection<PlayerHistory> PlayerHistory { get; set; }
        public virtual ICollection<TeamsDetails> TeamsDetails { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<TeamStandingGame> TeamStandingGames { get; set; }
        public virtual ICollection<NotesMessage> NotesMessages { get; set; }
    }
}
