//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamStanding
    {
        public int Id { get; set; }
        public int Rank { get; set; }
        public string Team { get; set; }
        public byte Games { get; set; }
        public byte Wins { get; set; }
        public byte Lost { get; set; }
        public int Pts { get; set; }
        public string Papf { get; set; }
        public string Home { get; set; }
        public string Road { get; set; }
        public string ScoreHome { get; set; }
        public string ScoreRoad { get; set; }
        public string Last5 { get; set; }
        public Nullable<int> TeamStandingGamesId { get; set; }
        public string PlusMinusField { get; set; }
    
        public virtual TeamStandingGame TeamStandingGame { get; set; }
    }
}
