//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnionsDoc
    {
        public int DocId { get; set; }
        public int UnionId { get; set; }
        public string FileName { get; set; }
        public byte[] DocFile { get; set; }
        public bool IsArchive { get; set; }
    
        public virtual Union Union { get; set; }
    }
}
