//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Union
    {
        public Union()
        {
            this.UnionsDocs = new HashSet<UnionsDoc>();
            this.Leagues = new HashSet<League>();
            this.UsersJobs = new HashSet<UsersJob>();
            this.SentMessages = new HashSet<SentMessage>();
            this.Seasons = new HashSet<Season>();
            this.Clubs = new HashSet<Club>();
            this.Auditoriums = new HashSet<Auditorium>();
        }
    
        public int UnionId { get; set; }
        public int SectionId { get; set; }
        public string Name { get; set; }
        public bool IsArchive { get; set; }
        public string Logo { get; set; }
        public string PrimaryImage { get; set; }
        public string Description { get; set; }
        public string IndexImage { get; set; }
        public string IndexAbout { get; set; }
        public string TermsCondition { get; set; }
        public string ContactPhone { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsHadicapEnabled { get; set; }
    
        public virtual Section Section { get; set; }
        public virtual ICollection<UnionsDoc> UnionsDocs { get; set; }
        public virtual ICollection<League> Leagues { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
        public virtual ICollection<SentMessage> SentMessages { get; set; }
        public virtual ICollection<Season> Seasons { get; set; }
        public virtual ICollection<Club> Clubs { get; set; }
        public virtual ICollection<Auditorium> Auditoriums { get; set; }
    }
}
