//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersType
    {
        public UsersType()
        {
            this.Users = new HashSet<User>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
        public string TypeRole { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
