//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersDvice
    {
        public int DeviceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string DeviceToken { get; set; }
        public Nullable<int> ServiceToken { get; set; }
        public Nullable<UserDeviceType> DeviceType { get; set; }
        public Nullable<NotificationServiceType> ServiceType { get; set; }
        public string EndpointArn { get; set; }
        public Nullable<int> SectionId { get; set; }
    
        public virtual User User { get; set; }
    }
}
