//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.UsersFriends = new HashSet<UsersFriend>();
            this.Friends = new HashSet<UsersFriend>();
            this.TeamsFans = new HashSet<TeamsFan>();
            this.TeamsPlayers = new HashSet<TeamsPlayer>();
            this.UsersGamesCycles = new HashSet<GamesCycle>();
            this.NotesRecipients = new HashSet<NotesRecipient>();
            this.Messages = new HashSet<Message>();
            this.WallThreads = new HashSet<WallThread>();
            this.UsersDvices = new HashSet<UsersDvice>();
            this.FansGamesCycles = new HashSet<GamesCycle>();
            this.Notifications = new HashSet<Notification>();
            this.PlayerHistory = new HashSet<PlayerHistory>();
            this.UsersJobs = new HashSet<UsersJob>();
        }
    
        public int UserId { get; set; }
        public int TypeId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string IdentNum { get; set; }
        public bool IsActive { get; set; }
        public string Password { get; set; }
        public string PassHint { get; set; }
        public int TriesNum { get; set; }
        public bool IsBlocked { get; set; }
        public string SessionId { get; set; }
        public bool IsArchive { get; set; }
        public string FullName { get; set; }
        public string IdentCard { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public Nullable<int> Height { get; set; }
        public string City { get; set; }
        public string Image { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string FbId { get; set; }
        public string Telephone { get; set; }
        public Nullable<bool> MedicalCertificate { get; set; }
        public Nullable<bool> Insurance { get; set; }
        public Nullable<int> LangId { get; set; }
        public int TestResults { get; set; }
    
        public virtual UsersType UsersType { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual ICollection<UsersFriend> UsersFriends { get; set; }
        public virtual ICollection<UsersFriend> Friends { get; set; }
        public virtual ICollection<TeamsFan> TeamsFans { get; set; }
        public virtual ICollection<TeamsPlayer> TeamsPlayers { get; set; }
        public virtual ICollection<GamesCycle> UsersGamesCycles { get; set; }
        public virtual ICollection<NotesRecipient> NotesRecipients { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<WallThread> WallThreads { get; set; }
        public virtual ICollection<UsersDvice> UsersDvices { get; set; }
        public virtual ICollection<GamesCycle> FansGamesCycles { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual ICollection<PlayerHistory> PlayerHistory { get; set; }
        public virtual ICollection<UsersJob> UsersJobs { get; set; }
    }
}
