//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WallThread
    {
        public WallThread()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TeamId { get; set; }
        public Nullable<int> GameId { get; set; }
        public bool IsArchive { get; set; }
        public int CreaterId { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual Team Team { get; set; }
        public virtual GamesCycle GamesCycle { get; set; }
        public virtual User User { get; set; }
    }
}
