//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מערכות.
        /// </summary>
        internal static string Acts {
            get {
                return ResourceManager.GetString("Acts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס מערכות.
        /// </summary>
        internal static string ActsRatio {
            get {
                return ResourceManager.GetString("ActsRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס סלים.
        /// </summary>
        internal static string BasketRatio {
            get {
                return ResourceManager.GetString("BasketRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיקו.
        /// </summary>
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלה מורחבת.
        /// </summary>
        internal static string ExtendedTable {
            get {
                return ResourceManager.GetString("ExtendedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחקים.
        /// </summary>
        internal static string GamesNum {
            get {
                return ResourceManager.GetString("GamesNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס שערים.
        /// </summary>
        internal static string GoalRatio {
            get {
                return ResourceManager.GetString("GoalRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to על הליגה.
        /// </summary>
        internal static string LeagueStructure {
            get {
                return ResourceManager.GetString("LeagueStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפסדים.
        /// </summary>
        internal static string LossNum {
            get {
                return ResourceManager.GetString("LossNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס נקודות.
        /// </summary>
        internal static string PointsRatio {
            get {
                return ResourceManager.GetString("PointsRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבוצה.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tec.
        /// </summary>
        internal static string TechLossesNum {
            get {
                return ResourceManager.GetString("TechLossesNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניצחונות.
        /// </summary>
        internal static string WinsNum {
            get {
                return ResourceManager.GetString("WinsNum", resourceCulture);
            }
        }
    }
}
