//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אימייל כבר קיים במערכת.
        /// </summary>
        internal static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שגיאה בהעלאת קובץ.
        /// </summary>
        internal static string ErrorUploadingFile {
            get {
                return ResourceManager.GetString("ErrorUploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook ID לא נמצא.
        /// </summary>
        internal static string FacebookIdNotFound {
            get {
                return ResourceManager.GetString("FacebookIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook משתמש לא נמצא.
        /// </summary>
        internal static string FacebookUserNotFound {
            get {
                return ResourceManager.GetString("FacebookUserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גמר.
        /// </summary>
        internal static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אחרונות.
        /// </summary>
        internal static string FinalNumber {
            get {
                return ResourceManager.GetString("FinalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמינית גמר.
        /// </summary>
        internal static string Final_Eighth {
            get {
                return ResourceManager.GetString("Final_Eighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם המשתמש או הסיסמא שגויים.
        /// </summary>
        internal static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קובץ חסר.
        /// </summary>
        internal static string NoFileContent {
            get {
                return ResourceManager.GetString("NoFileContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר זיהוי לא נמצא.
        /// </summary>
        internal static string PersonalIdMissing {
            get {
                return ResourceManager.GetString("PersonalIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רבע גמר.
        /// </summary>
        internal static string Quarter_finals {
            get {
                return ResourceManager.GetString("Quarter_finals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חצי גמר.
        /// </summary>
        internal static string Semifinals {
            get {
                return ResourceManager.GetString("Semifinals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלב.
        /// </summary>
        internal static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משתמש כבר קיים במערכת.
        /// </summary>
        internal static string UsernameExists {
            get {
                return ResourceManager.GetString("UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם המששתמה או הסיסמה חסרים.
        /// </summary>
        internal static string UsernameOrPassMissing {
            get {
                return ResourceManager.GetString("UsernameOrPassMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשתמש לא פעיל.
        /// </summary>
        internal static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשתמש לא קיים במערכת.
        /// </summary>
        internal static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משתמש לא נמצא.
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
