//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פעיל.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מערכות.
        /// </summary>
        internal static string Acts {
            get {
                return ResourceManager.GetString("Acts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס מערכות.
        /// </summary>
        internal static string ActsRatio {
            get {
                return ResourceManager.GetString("ActsRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף מערכה.
        /// </summary>
        internal static string AddAct {
            get {
                return ResourceManager.GetString("AddAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספת אירוע.
        /// </summary>
        internal static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף אירוע למועדון.
        /// </summary>
        internal static string AddEventToClub {
            get {
                return ResourceManager.GetString("AddEventToClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוספת אירוע לליגה.
        /// </summary>
        internal static string AddEventToLeague {
            get {
                return ResourceManager.GetString("AddEventToLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צרף קובץ.
        /// </summary>
        internal static string AddFile {
            get {
                return ResourceManager.GetString("AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף משחק.
        /// </summary>
        internal static string AddGame {
            get {
                return ResourceManager.GetString("AddGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף משחק בשלב.
        /// </summary>
        internal static string AddGameToStage {
            get {
                return ResourceManager.GetString("AddGameToStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף בית.
        /// </summary>
        internal static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף חדש.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף שחקן חדש.
        /// </summary>
        internal static string AddNewPlayer {
            get {
                return ResourceManager.GetString("AddNewPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף כקבוצה חדשה.
        /// </summary>
        internal static string AddNewTeam {
            get {
                return ResourceManager.GetString("AddNewTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף רבע.
        /// </summary>
        internal static string AddQuarter {
            get {
                return ResourceManager.GetString("AddQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף שלב.
        /// </summary>
        internal static string AddStage {
            get {
                return ResourceManager.GetString("AddStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף קבוצה.
        /// </summary>
        internal static string AddTeam {
            get {
                return ResourceManager.GetString("AddTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקם טורניר.
        /// </summary>
        internal static string AddTournament {
            get {
                return ResourceManager.GetString("AddTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנהל מערכת.
        /// </summary>
        internal static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קטגוריה.
        /// </summary>
        internal static string Ages {
            get {
                return ResourceManager.GetString("Ages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכל.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כל המחזורים.
        /// </summary>
        internal static string AllCycles {
            get {
                return ResourceManager.GetString("AllCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פעולה זאת תסיר את הפריט מהרשימה ותעביר אותה לתיקיית הארכיון.
        ///
        ///לחץ לאישור.
        /// </summary>
        internal static string ArchiveConfirm {
            get {
                return ResourceManager.GetString("ArchiveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנהל איגוד.
        /// </summary>
        internal static string AssociationAdmin {
            get {
                return ResourceManager.GetString("AssociationAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר עמותה.
        /// </summary>
        internal static string AssociationNumber {
            get {
                return ResourceManager.GetString("AssociationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כתובת אולם.
        /// </summary>
        internal static string Auditorium {
            get {
                return ResourceManager.GetString("Auditorium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האולם כבר נמצא.
        /// </summary>
        internal static string AuditoriumAlreadyExsits {
            get {
                return ResourceManager.GetString("AuditoriumAlreadyExsits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אולמות.
        /// </summary>
        internal static string Auditoriums {
            get {
                return ResourceManager.GetString("Auditoriums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס סלים.
        /// </summary>
        internal static string BasketRatio {
            get {
                return ResourceManager.GetString("BasketRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מתחילת החודש.
        /// </summary>
        internal static string BeginningOfMonth {
            get {
                return ResourceManager.GetString("BeginningOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך לידה.
        /// </summary>
        internal static string BirthDay {
            get {
                return ResourceManager.GetString("BirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חסום.
        /// </summary>
        internal static string Blocked {
            get {
                return ResourceManager.GetString("Blocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חישוב הפחתות.
        /// </summary>
        internal static string CalculatedReduction {
            get {
                return ResourceManager.GetString("CalculatedReduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בטל.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  שנה סדר שלבים.
        /// </summary>
        internal static string ChangeOrderStages {
            get {
                return ResourceManager.GetString("ChangeOrderStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to glyphicon glyphicon-chevron-left.
        /// </summary>
        internal static string ChevronCss {
            get {
                return ResourceManager.GetString("ChevronCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יישוב.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סגור.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות.
        /// </summary>
        internal static string ClubAbout {
            get {
                return ResourceManager.GetString("ClubAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיאור.
        /// </summary>
        internal static string ClubDescription {
            get {
                return ResourceManager.GetString("ClubDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מידע.
        /// </summary>
        internal static string ClubInformationTab {
            get {
                return ResourceManager.GetString("ClubInformationTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ראשי.
        /// </summary>
        internal static string ClubMainTab {
            get {
                return ResourceManager.GetString("ClubMainTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנהל מועדון.
        /// </summary>
        internal static string ClubManager {
            get {
                return ResourceManager.GetString("ClubManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string ClubName {
            get {
                return ResourceManager.GetString("ClubName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בעלי-תפקידים.
        /// </summary>
        internal static string ClubOfficialsTab {
            get {
                return ResourceManager.GetString("ClubOfficialsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אגודות.
        /// </summary>
        internal static string ClubsInSection {
            get {
                return ResourceManager.GetString("ClubsInSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תנאי המועדון.
        /// </summary>
        internal static string ClubTermsCondition {
            get {
                return ResourceManager.GetString("ClubTermsCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מאמן.
        /// </summary>
        internal static string Coach {
            get {
                return ResourceManager.GetString("Coach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רשימת קבוצות כללית.
        /// </summary>
        internal static string CommonTeamsList {
            get {
                return ResourceManager.GetString("CommonTeamsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אנא אשר יצירת לוח משחקים חדש עבור שלב {0}.
        /// </summary>
        internal static string ConfirmNewGamesTable {
            get {
                return ResourceManager.GetString("ConfirmNewGamesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אנא אשר איפוס משחק זה.
        /// </summary>
        internal static string ConfirmResetGame {
            get {
                return ResourceManager.GetString("ConfirmResetGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מדינה.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צור לוח משחקים.
        /// </summary>
        internal static string CreateGamesTable {
            get {
                return ResourceManager.GetString("CreateGamesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הוסף ליגה.
        /// </summary>
        internal static string CreateLeague {
            get {
                return ResourceManager.GetString("CreateLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to צור קבוצה חדשה.
        /// </summary>
        internal static string CreateNewTeam {
            get {
                return ResourceManager.GetString("CreateNewTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  הוסף טורניר.
        /// </summary>
        internal static string CreateTournament {
            get {
                return ResourceManager.GetString("CreateTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחזור.
        /// </summary>
        internal static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנתונים נשמרו בהצלחה.
        /// </summary>
        internal static string DataSavedSuccess {
            get {
                return ResourceManager.GetString("DataSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy HH:mm.
        /// </summary>
        internal static string DateFormat {
            get {
                return ResourceManager.GetString("DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך/ שעה.
        /// </summary>
        internal static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחק.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא אשר מחיקת פריט.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קודם יש למחוק את ליגות האיגוד.
        /// </summary>
        internal static string DeleteLeaguesFirst {
            get {
                return ResourceManager.GetString("DeleteLeaguesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא אשר מחיקת פריטים שנבחרו.
        /// </summary>
        internal static string DeleteListConfirm {
            get {
                return ResourceManager.GetString("DeleteListConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קודם יש למחוק את קבוצות הליגה.
        /// </summary>
        internal static string DeleteTeamsFirst {
            get {
                return ResourceManager.GetString("DeleteTeamsFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרטים.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rtl.
        /// </summary>
        internal static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליגה.
        /// </summary>
        internal static string Division {
            get {
                return ResourceManager.GetString("Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תיקו.
        /// </summary>
        internal static string Draw {
            get {
                return ResourceManager.GetString("Draw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ערוך.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עורך.
        /// </summary>
        internal static string Editors {
            get {
                return ResourceManager.GetString("Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טורניר אילת.
        /// </summary>
        internal static string EilatTournament {
            get {
                return ResourceManager.GetString("EilatTournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אימייל.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דואל {0} קיים כבר במערכת.
        /// </summary>
        internal static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נגמר.
        /// </summary>
        internal static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיים משחק.
        /// </summary>
        internal static string EndGame {
            get {
                return ResourceManager.GetString("EndGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תקלה ביצירת לוח משחקים וודא שהשלב האחרון מכיל בתים..
        /// </summary>
        internal static string ErrorGamesTableCreation {
            get {
                return ResourceManager.GetString("ErrorGamesTableCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא להכניס מספר חיובי.
        /// </summary>
        internal static string Error_PositiveNumbersOnly {
            get {
                return ResourceManager.GetString("Error_PositiveNumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ארוע.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אירועים.
        /// </summary>
        internal static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצוא דוח שופטים.
        /// </summary>
        internal static string ExportReferees {
            get {
                return ResourceManager.GetString("ExportReferees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצוא לאקסל.
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דיווח איגוד.
        /// </summary>
        internal static string ExportUnionReport {
            get {
                return ResourceManager.GetString("ExportUnionReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלה מורחבת.
        /// </summary>
        internal static string ExtendedTable {
            get {
                return ResourceManager.GetString("ExtendedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קישור חיצוני.
        /// </summary>
        internal static string ExternalLink {
            get {
                return ResourceManager.GetString("ExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אוהד.
        /// </summary>
        internal static string Fans {
            get {
                return ResourceManager.GetString("Fans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נקבה.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לרשום מספרים בלבד.
        /// </summary>
        internal static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקובץ לא תקין.
        /// </summary>
        internal static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משקל הקובץ לא תקין.
        /// </summary>
        internal static string FileSizeError {
            get {
                return ResourceManager.GetString("FileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג.
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גמר.
        /// </summary>
        internal static string Final {
            get {
                return ResourceManager.GetString("Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אחרונות.
        /// </summary>
        internal static string FinalNumber {
            get {
                return ResourceManager.GetString("FinalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמינית גמר.
        /// </summary>
        internal static string Final_Eighth {
            get {
                return ResourceManager.GetString("Final_Eighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מחזור ראשון.
        /// </summary>
        internal static string FirstGameStart {
            get {
                return ResourceManager.GetString("FirstGameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם מלא.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נק למשחק.
        /// </summary>
        internal static string GamePaPf {
            get {
                return ResourceManager.GetString("GamePaPf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מש&apos;.
        /// </summary>
        internal static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ימי משחק.
        /// </summary>
        internal static string GamesDays {
            get {
                return ResourceManager.GetString("GamesDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות משחק.
        /// </summary>
        internal static string GameSettings {
            get {
                return ResourceManager.GetString("GameSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זמן בין משחקים (בשעות).
        /// </summary>
        internal static string GamesInterval {
            get {
                return ResourceManager.GetString("GamesInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחקים.
        /// </summary>
        internal static string GamesNum {
            get {
                return ResourceManager.GetString("GamesNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוח משחקים.
        /// </summary>
        internal static string GamesTable {
            get {
                return ResourceManager.GetString("GamesTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL כתובת.
        /// </summary>
        internal static string GamesUrl {
            get {
                return ResourceManager.GetString("GamesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוג המשחק.
        /// </summary>
        internal static string GameType {
            get {
                return ResourceManager.GetString("GameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מין.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס שערים.
        /// </summary>
        internal static string GoalRatio {
            get {
                return ResourceManager.GetString("GoalRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מערכת זהב.
        /// </summary>
        internal static string GoldenSet {
            get {
                return ResourceManager.GetString("GoldenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בית.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם בית.
        /// </summary>
        internal static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בתים.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד קבוצת חוץ.
        /// </summary>
        internal static string GuesTeamPoints {
            get {
                return ResourceManager.GetString("GuesTeamPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ק. חוץ.
        /// </summary>
        internal static string GuestTeam {
            get {
                return ResourceManager.GetString("GuestTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בסיס ניקוד נכות.
        /// </summary>
        internal static string HandicapLevel {
            get {
                return ResourceManager.GetString("HandicapLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התאמה לנכים.
        /// </summary>
        internal static string Handicapped {
            get {
                return ResourceManager.GetString("Handicapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גובה (ס&quot;מ).
        /// </summary>
        internal static string Heigth {
            get {
                return ResourceManager.GetString("Heigth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טקסט זה יוצג באופן מודגש בקישור החיצוני של טבלת הליגה.
        /// </summary>
        internal static string HelpTextAboutLeague {
            get {
                return ResourceManager.GetString("HelpTextAboutLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ראשי.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ק. בית.
        /// </summary>
        internal static string HomeTeam {
            get {
                return ResourceManager.GetString("HomeTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד קבוצת בית.
        /// </summary>
        internal static string HomeTeamPoints {
            get {
                return ResourceManager.GetString("HomeTeamPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ת&quot;ז.
        /// </summary>
        internal static string IdentNum {
            get {
                return ResourceManager.GetString("IdentNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; תז {0} קיים כבר במערכת.
        /// </summary>
        internal static string IdIsAlreadyExists {
            get {
                return ResourceManager.GetString("IdIsAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תמונה.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יבוא מאקסל.
        /// </summary>
        internal static string ImportFromExcel {
            get {
                return ResourceManager.GetString("ImportFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מידע.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ביטוח.
        /// </summary>
        internal static string Insurance {
            get {
                return ResourceManager.GetString("Insurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך סיום ביטוח.
        /// </summary>
        internal static string InsuranceDate {
            get {
                return ResourceManager.GetString("InsuranceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טעינת אישור רפואי.
        /// </summary>
        internal static string InsuranceFile {
            get {
                return ResourceManager.GetString("InsuranceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זמן לא חוקי.
        /// </summary>
        internal static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסם באפליקציה.
        /// </summary>
        internal static string IsPublished {
            get {
                return ResourceManager.GetString("IsPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is published.
        /// </summary>
        internal static string IsPublishedGameCycle {
            get {
                return ResourceManager.GetString("IsPublishedGameCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם קבוצת עתודה?.
        /// </summary>
        internal static string IsReserved {
            get {
                return ResourceManager.GetString("IsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 אותיות ומספרים באנגלית עם רצף של עד 3 תווים.
        /// </summary>
        internal static string IvalidPasswrodPattern {
            get {
                return ResourceManager.GetString("IvalidPasswrodPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נוק-אאוט.
        /// </summary>
        internal static string Knockout {
            get {
                return ResourceManager.GetString("Knockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to he.
        /// </summary>
        internal static string Lang {
            get {
                return ResourceManager.GetString("Lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שפה.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5אחרונים.
        /// </summary>
        internal static string Last5 {
            get {
                return ResourceManager.GetString("Last5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליגה.
        /// </summary>
        internal static string League {
            get {
                return ResourceManager.GetString("League", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to על הליגה.
        /// </summary>
        internal static string LeagueAbout {
            get {
                return ResourceManager.GetString("LeagueAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנהל ליגה.
        /// </summary>
        internal static string LeagueAdmin {
            get {
                return ResourceManager.GetString("LeagueAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קוד ליגה.
        /// </summary>
        internal static string LeagueCode {
            get {
                return ResourceManager.GetString("LeagueCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם הליגה.
        /// </summary>
        internal static string LeagueName {
            get {
                return ResourceManager.GetString("LeagueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ליגות.
        /// </summary>
        internal static string Leagues {
            get {
                return ResourceManager.GetString("Leagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מבנה הליגה.
        /// </summary>
        internal static string LeagueStructure {
            get {
                return ResourceManager.GetString("LeagueStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלת ליגה.
        /// </summary>
        internal static string LeagueTable {
            get {
                return ResourceManager.GetString("LeagueTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לוגו.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התנתק.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מפסידה.
        /// </summary>
        internal static string Loser {
            get {
                return ResourceManager.GetString("Loser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפ&apos;.
        /// </summary>
        internal static string Loss {
            get {
                return ResourceManager.GetString("Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפסדים.
        /// </summary>
        internal static string LossNum {
            get {
                return ResourceManager.GetString("LossNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ראשי.
        /// </summary>
        internal static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to זכר.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מערכת ניהול.
        /// </summary>
        internal static string ManagementSystem {
            get {
                return ResourceManager.GetString("ManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד נכות מקסימאלי.
        /// </summary>
        internal static string MaximumHandicapScoreValue {
            get {
                return ResourceManager.GetString("MaximumHandicapScoreValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxLengthAboutLeague {
            get {
                return ResourceManager.GetString("MaxLengthAboutLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MaxLengthLeagueStructure {
            get {
                return ResourceManager.GetString("MaxLengthLeagueStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אישור רפואי.
        /// </summary>
        internal static string MedicalCertificate {
            get {
                return ResourceManager.GetString("MedicalCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to גברים.
        /// </summary>
        internal static string Men {
            get {
                return ResourceManager.GetString("Men", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הודעה.
        /// </summary>
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קביעת גיל מנימום.
        /// </summary>
        internal static string MinimumAge {
            get {
                return ResourceManager.GetString("MinimumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to להעביר.
        /// </summary>
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הזז מחזור.
        /// </summary>
        internal static string MoveCycle {
            get {
                return ResourceManager.GetString("MoveCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העבר שחקן.
        /// </summary>
        internal static string MovePlayer {
            get {
                return ResourceManager.GetString("MovePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העבר לקבוצה אחרת.
        /// </summary>
        internal static string MovePlayerToTeam {
            get {
                return ResourceManager.GetString("MovePlayerToTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העבר לליגה אחרת.
        /// </summary>
        internal static string MoveTeamToLeague {
            get {
                return ResourceManager.GetString("MoveTeamToLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העבר לליגה אחרת.
        /// </summary>
        internal static string MoveToLeague {
            get {
                return ResourceManager.GetString("MoveToLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מרכז ספורט.
        /// </summary>
        internal static string NameSportCenter {
            get {
                return ResourceManager.GetString("NameSportCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; עמותה.
        /// </summary>
        internal static string NGO_Number {
            get {
                return ResourceManager.GetString("NGO_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין נתונים.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לא נבחרו משחקים מתאימים.
        /// </summary>
        internal static string NoGamesFound {
            get {
                return ResourceManager.GetString("NoGamesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אין לך הרשאה לראות דף זה..
        /// </summary>
        internal static string NotAuthorizedPage {
            get {
                return ResourceManager.GetString("NotAuthorizedPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התראות.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ בעלי תפקידים.
        /// </summary>
        internal static string NumberOfOfficials {
            get {
                return ResourceManager.GetString("NumberOfOfficials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סה&quot;כ שחקנים.
        /// </summary>
        internal static string NumberOfPlayers {
            get {
                return ResourceManager.GetString("NumberOfPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הדף שביקשת לא נמצא.
        /// </summary>
        internal static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נק/ נק יריבה.
        /// </summary>
        internal static string Papf {
            get {
                return ResourceManager.GetString("Papf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to דרכון.
        /// </summary>
        internal static string PassportNum {
            get {
                return ResourceManager.GetString("PassportNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סיסמה.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תקופה.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הרשאה.
        /// </summary>
        internal static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תמונת הסגל.
        /// </summary>
        internal static string PersonnelImage {
            get {
                return ResourceManager.GetString("PersonnelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טלפון.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקום.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקום האירוע.
        /// </summary>
        internal static string PlaceOfEvent {
            get {
                return ResourceManager.GetString("PlaceOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מקומות.
        /// </summary>
        internal static string Places {
            get {
                return ResourceManager.GetString("Places", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחקן.
        /// </summary>
        internal static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השחקן כבר קיים בקבוצה זו.
        /// </summary>
        internal static string PlayerAlreadyInTeam {
            get {
                return ResourceManager.GetString("PlayerAlreadyInTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השחקן כבר בתפקיד זה.
        /// </summary>
        internal static string PlayerAlreadyOnThisPosition {
            get {
                return ResourceManager.GetString("PlayerAlreadyOnThisPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; כרטיס שחקן.
        /// </summary>
        internal static string PlayerCardNumber {
            get {
                return ResourceManager.GetString("PlayerCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to משחק פחות מ-3 שנים.
        /// </summary>
        internal static string PlayereInTeamLessThan3year {
            get {
                return ResourceManager.GetString("PlayereInTeamLessThan3year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to השחקן לא נמצא.
        /// </summary>
        internal static string PlayerNotExists {
            get {
                return ResourceManager.GetString("PlayerNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שחקנים.
        /// </summary>
        internal static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פלייאוף.
        /// </summary>
        internal static string Playoff {
            get {
                return ResourceManager.GetString("Playoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נק&apos;.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס נקודות.
        /// </summary>
        internal static string PointsRatio {
            get {
                return ResourceManager.GetString("PointsRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בריכות.
        /// </summary>
        internal static string Pools {
            get {
                return ResourceManager.GetString("Pools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפקיד.
        /// </summary>
        internal static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוגי שחקנים.
        /// </summary>
        internal static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הדפס.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שדה חובה.
        /// </summary>
        internal static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נא אשר פרסום פריטים שנבחרו.
        /// </summary>
        internal static string PublishConfirm {
            get {
                return ResourceManager.GetString("PublishConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רבעים.
        /// </summary>
        internal static string Quarters {
            get {
                return ResourceManager.GetString("Quarters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רבע גמר.
        /// </summary>
        internal static string Quarter_finals {
            get {
                return ResourceManager.GetString("Quarter_finals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בין תאריכים.
        /// </summary>
        internal static string Ranged {
            get {
                return ResourceManager.GetString("Ranged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך סיום.
        /// </summary>
        internal static string RangeEnd {
            get {
                return ResourceManager.GetString("RangeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך התחלה.
        /// </summary>
        internal static string RangeStart {
            get {
                return ResourceManager.GetString("RangeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מיקום.
        /// </summary>
        internal static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שופט.
        /// </summary>
        internal static string Referee {
            get {
                return ResourceManager.GetString("Referee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רענן.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אפס משחק.
        /// </summary>
        internal static string ResetGame {
            get {
                return ResourceManager.GetString("ResetGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד מאופס.
        /// </summary>
        internal static string ResetScores {
            get {
                return ResourceManager.GetString("ResetScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שינוי משחק זה, יעדכן בהתאם את כל המשחקים הקשורים אליו, האם אתה בטוח?.
        /// </summary>
        internal static string ResetWarning {
            get {
                return ResourceManager.GetString("ResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נצ/ הפ- חוץ.
        /// </summary>
        internal static string Road {
            get {
                return ResourceManager.GetString("Road", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תפקיד.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התפקיד לא קיים במערכת.
        /// </summary>
        internal static string RoleNotExists {
            get {
                return ResourceManager.GetString("RoleNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סוגי תפקידים.
        /// </summary>
        internal static string RolesTypes {
            get {
                return ResourceManager.GetString("RolesTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר סיבובים.
        /// </summary>
        internal static string RoundsNumber {
            get {
                return ResourceManager.GetString("RoundsNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שמור.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאה.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נק למשחק - בית.
        /// </summary>
        internal static string ScoreHome {
            get {
                return ResourceManager.GetString("ScoreHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נק למשחק- חוץ.
        /// </summary>
        internal static string ScoreRoad {
            get {
                return ResourceManager.GetString("ScoreRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חפש.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חפש שם קיים.
        /// </summary>
        internal static string SearchName {
            get {
                return ResourceManager.GetString("SearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עונות.
        /// </summary>
        internal static string Seasons {
            get {
                return ResourceManager.GetString("Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ענף.
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם הענף.
        /// </summary>
        internal static string SectionName {
            get {
                return ResourceManager.GetString("SectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ענפים.
        /// </summary>
        internal static string Sections {
            get {
                return ResourceManager.GetString("Sections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - בחר -.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to פרסם באפליקציה.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר את כולם.
        /// </summary>
        internal static string SelectAllPlayers {
            get {
                return ResourceManager.GetString("SelectAllPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר את כל הקבוצות.
        /// </summary>
        internal static string SelectAllTeams {
            get {
                return ResourceManager.GetString("SelectAllTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר לאיזה ליגה להעביר.
        /// </summary>
        internal static string SelectLeagueToMove {
            get {
                return ResourceManager.GetString("SelectLeagueToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לבחור קבוצה אחרת.
        /// </summary>
        internal static string SelectOtherTeam {
            get {
                return ResourceManager.GetString("SelectOtherTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קבוצה.
        /// </summary>
        internal static string SelectTeam {
            get {
                return ResourceManager.GetString("SelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר קובץ  {0} תקין.
        /// </summary>
        internal static string SelectValidFile {
            get {
                return ResourceManager.GetString("SelectValidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יש לבחור קובץ jpg.
        /// </summary>
        internal static string SelectValidImage {
            get {
                return ResourceManager.GetString("SelectValidImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חצי גמר.
        /// </summary>
        internal static string Semifinals {
            get {
                return ResourceManager.GetString("Semifinals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלח.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; מחזורים רצופים.
        /// </summary>
        internal static string SequenceRounds {
            get {
                return ResourceManager.GetString("SequenceRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In a row every week.
        /// </summary>
        internal static string SequenceRounds0 {
            get {
                return ResourceManager.GetString("SequenceRounds0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One week on, One week off.
        /// </summary>
        internal static string SequenceRounds1 {
            get {
                return ResourceManager.GetString("SequenceRounds1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two weeks on, One week off.
        /// </summary>
        internal static string SequenceRounds2 {
            get {
                return ResourceManager.GetString("SequenceRounds2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יחס המערכות.
        /// </summary>
        internal static string SetDiffs {
            get {
                return ResourceManager.GetString("SetDiffs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד ידני.
        /// </summary>
        internal static string SetTheScoresManualy {
            get {
                return ResourceManager.GetString("SetTheScoresManualy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הגדרות.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חולצה.
        /// </summary>
        internal static string Shirt {
            get {
                return ResourceManager.GetString("Shirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר חולצה כבר קיים.
        /// </summary>
        internal static string ShirtAlreadyExists {
            get {
                return ResourceManager.GetString("ShirtAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מס&apos; חולצה.
        /// </summary>
        internal static string ShirtNumber {
            get {
                return ResourceManager.GetString("ShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג רשימה כרונולוגית.
        /// </summary>
        internal static string ShowGamesChronological {
            get {
                return ResourceManager.GetString("ShowGamesChronological", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to חזור לתצוגת מחזורים.
        /// </summary>
        internal static string ShowGamesStages {
            get {
                return ResourceManager.GetString("ShowGamesStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הצג קובץ.
        /// </summary>
        internal static string ShowTerms {
            get {
                return ResourceManager.GetString("ShowTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לפי אולם.
        /// </summary>
        internal static string SortArea {
            get {
                return ResourceManager.GetString("SortArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לפי תאריך.
        /// </summary>
        internal static string SortTime {
            get {
                return ResourceManager.GetString("SortTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שלב.
        /// </summary>
        internal static string Stage {
            get {
                return ResourceManager.GetString("Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טבלה.
        /// </summary>
        internal static string Standings {
            get {
                return ResourceManager.GetString("Standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תאריך התחלה.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחיל.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to התחל משחק.
        /// </summary>
        internal static string StartGame {
            get {
                return ResourceManager.GetString("StartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to סטאטוס.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to החלף.
        /// </summary>
        internal static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שגיאת מערכת.
        /// </summary>
        internal static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבוצה.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנהל קבוצה.
        /// </summary>
        internal static string TeamAdmin {
            get {
                return ResourceManager.GetString("TeamAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקבוצה כבר בליגה.
        /// </summary>
        internal static string TeamExists {
            get {
                return ResourceManager.GetString("TeamExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הקבוצה לא נמצאת במערכת.
        /// </summary>
        internal static string TeamNotFound {
            get {
                return ResourceManager.GetString("TeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קבוצות.
        /// </summary>
        internal static string Teams {
            get {
                return ResourceManager.GetString("Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מספר קבוצות.
        /// </summary>
        internal static string TeamsNum {
            get {
                return ResourceManager.GetString("TeamsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הפסד טכני.
        /// </summary>
        internal static string TechLoss {
            get {
                return ResourceManager.GetString("TechLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טכני.
        /// </summary>
        internal static string TechLossesNum {
            get {
                return ResourceManager.GetString("TechLossesNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נצחון טכני.
        /// </summary>
        internal static string TechWin {
            get {
                return ResourceManager.GetString("TechWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to קובץ תקנון.
        /// </summary>
        internal static string TermsFile {
            get {
                return ResourceManager.GetString("TermsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to תוצאת בדיקה רפואית.
        /// </summary>
        internal static string TestResults {
            get {
                return ResourceManager.GetString("TestResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כותרת.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הכותרת של האירוע.
        /// </summary>
        internal static string TitleOfEvent {
            get {
                return ResourceManager.GetString("TitleOfEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to לאירוע.
        /// </summary>
        internal static string ToEvent {
            get {
                return ResourceManager.GetString("ToEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to למשחק.
        /// </summary>
        internal static string ToGame {
            get {
                return ResourceManager.GetString("ToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יצא את לוח המשחקים לאקסל.
        /// </summary>
        internal static string TooltipExportToExcel {
            get {
                return ResourceManager.GetString("TooltipExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to יבא את לוח המשחקים חזרה מאקסל על מנת לעדכן את השעות והתאריכים של המשחקים.
        /// </summary>
        internal static string TooltipImportFromExcel {
            get {
                return ResourceManager.GetString("TooltipImportFromExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to העבר את הקבוצה/ות הנבחרת/ות לליגה אחרת.
        /// </summary>
        internal static string TooltipMoveToLeague {
            get {
                return ResourceManager.GetString("TooltipMoveToLeague", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בחר כדי לפרסם או לא לפרסם את הלוח משחקים באפליקציה ובקישורים החיצוניים.
        /// </summary>
        internal static string TooltipPublishApp {
            get {
                return ResourceManager.GetString("TooltipPublishApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניקוד נכות משוקלל.
        /// </summary>
        internal static string TotalResult {
            get {
                return ResourceManager.GetString("TotalResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טורניר.
        /// </summary>
        internal static string Tournament {
            get {
                return ResourceManager.GetString("Tournament", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to טורנירים.
        /// </summary>
        internal static string Tournaments {
            get {
                return ResourceManager.GetString("Tournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to האם תחת חסות בוגרים?.
        /// </summary>
        internal static string UnderAdult {
            get {
                return ResourceManager.GetString("UnderAdult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איגוד.
        /// </summary>
        internal static string Union {
            get {
                return ResourceManager.GetString("Union", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to אודות האיגוד.
        /// </summary>
        internal static string UnionDescription {
            get {
                return ResourceManager.GetString("UnionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מידע אינדקס איגוד.
        /// </summary>
        internal static string UnionIndex {
            get {
                return ResourceManager.GetString("UnionIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איגודים.
        /// </summary>
        internal static string Unions {
            get {
                return ResourceManager.GetString("Unions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to איגודים בענף.
        /// </summary>
        internal static string UnionsInSection {
            get {
                return ResourceManager.GetString("UnionsInSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to עדכן.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to רענן תוצאות משחק.
        /// </summary>
        internal static string UpdateGameResults {
            get {
                return ResourceManager.GetString("UpdateGameResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to הנך מבקש לבצע שינוי ידני בנתוני המשחק. 
        ///נא וודא שהשינוי לא יוצר התנגשות בין משחקים המתקיימים במועד זהה ובאותו אולם.
        /// </summary>
        internal static string UpdateGameWarnning {
            get {
                return ResourceManager.GetString("UpdateGameWarnning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשתמש כבר נמצא בתפקיד זה.
        /// </summary>
        internal static string UserAlreadyHasThisRole {
            get {
                return ResourceManager.GetString("UserAlreadyHasThisRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משתמש.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to שם משתמש כבר קיים במערכת.
        /// </summary>
        internal static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשתמש לא קיים במערכת.
        /// </summary>
        internal static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בהמתנה.
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to א,ב,ג,ד,ה,ו,ש.
        /// </summary>
        internal static string WeekDays {
            get {
                return ResourceManager.GetString("WeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניצחון.
        /// </summary>
        internal static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to מנצחת.
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניצ&apos;.
        /// </summary>
        internal static string Wins {
            get {
                return ResourceManager.GetString("Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נצ/ הפ- בית.
        /// </summary>
        internal static string WinsLostHome {
            get {
                return ResourceManager.GetString("WinsLostHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ניצחונות.
        /// </summary>
        internal static string WinsNum {
            get {
                return ResourceManager.GetString("WinsNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to המשך עם ניקוד מצטבר.
        /// </summary>
        internal static string WithTheirRecords {
            get {
                return ResourceManager.GetString("WithTheirRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to נשים.
        /// </summary>
        internal static string Women {
            get {
                return ResourceManager.GetString("Women", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to בעל תפקיד.
        /// </summary>
        internal static string Workers {
            get {
                return ResourceManager.GetString("Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to כן.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
